export const GET_ALL_USERS = 'GET_ALL_USERS'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const USER_LOADED = 'USER_LOADED'
export const SIGN_OUT='SIGN_OUT'
export const GET_CORDSWHEREWEARE = "GET_CORDSWHEREWEARE";
export const GET_INCIDENTS = "GET_INCIDENTS";
export const ADD_INCIDENT = "ADD_INCIDENT";
export const SET_RADIUS = "SET_RADIUS";
export const USER_POSITION = "USER_POSITION";
export const NEARBY_INCIDENTS = "NEARBY_INCIDENTS";
export const SET_INCIDENTS = "SET_INCIDENTS";
